name: Build Qt Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt and Build Essentials
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools

    - name: Run Qmake
      run: qmake lec_data.pro

    - name: Compile Project
      run: make
